# Generated by Django 4.2.6 on 2023-12-11 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20231130_1115'),
        ('progress_literasi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bukudibaca',
            name='buku',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.book'),
        ),
        migrations.AlterField(
            model_name='progressbaca',
            name='buku',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.book'),
        ),
    ]
