# Generated by Django 4.2.4 on 2023-12-16 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('progress_literasi', '0002_alter_bukudibaca_buku_alter_progressbaca_buku'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progressbaca',
            name='tanggal',
        ),
    ]
