# Generated by Django 4.2.6 on 2023-10-26 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress_literasi', '0002_bukudibaca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aktivitasuser',
            name='waktu_aktif',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bukudibaca',
            name='tanggal_dibaca',
            field=models.DateField(auto_now_add=True),
        ),
    ]
