# Generated by Django 4.2.6 on 2023-10-27 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_book_rating'),
        ('progress_literasi', '0003_alter_aktivitasuser_waktu_aktif_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bukudibaca',
            name='buku',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.book'),
        ),
        migrations.AlterField(
            model_name='progressbaca',
            name='buku',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.book'),
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
