# Generated by Django 4.2.4 on 2023-12-16 08:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('progress_literasi', '0003_remove_progressbaca_tanggal'),
    ]

    operations = [
        migrations.AddField(
            model_name='targetharian',
            name='tanggal',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
