# Generated by Django 4.2.6 on 2023-10-28 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('progress_literasi', '0004_alter_bukudibaca_buku_alter_progressbaca_buku_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bukudibaca',
            name='tanggal_dibaca',
        ),
    ]
