# Generated by Django 4.2.4 on 2023-12-16 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('progress_literasi', '0004_targetharian_tanggal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='targetharian',
            name='tanggal',
        ),
    ]
