# Generated by Django 4.2.6 on 2023-10-28 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress_literasi', '0005_remove_bukudibaca_tanggal_dibaca'),
    ]

    operations = [
        migrations.AddField(
            model_name='bukudibaca',
            name='counted',
            field=models.IntegerField(default=0),
        ),
    ]
