# Generated by Django 4.2.6 on 2023-10-29 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('progress_literasi', '0005_remove_bukudibaca_buku_remove_bukudibaca_user_and_more'),
        ('progress_literasi', '0007_remove_targetharian_tanggal_and_more'),
    ]

    operations = [
    ]
