# Generated by Django 4.2.6 on 2023-10-21 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('author', models.CharField(max_length=255, verbose_name='author')),
                ('isbn', models.CharField(max_length=150, verbose_name='isbn')),
                ('isbn13', models.CharField(max_length=150, verbose_name='isbn13')),
                ('num_pages', models.IntegerField(verbose_name='num_pages')),
                ('publication_date', models.DateField(verbose_name='publication_date')),
                ('publisher', models.CharField(max_length=255, verbose_name='publisher')),
            ],
        ),
    ]
