# Generated by Django 4.2.6 on 2023-10-21 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_book_author_book_authors_alter_book_isbn13_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='publisher',
        ),
    ]
