# Generated by Django 4.2.6 on 2023-10-21 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_book_publisher'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
