# Generated by Django 4.2.6 on 2023-10-21 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='isbn13',
        ),
    ]
