# Generated by Django 4.2.6 on 2023-10-21 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_remove_book_isbn13'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
