# Generated by Django 5.0 on 2023-12-15 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detail_buku', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='likes_count',
            field=models.IntegerField(default=0),
        ),
    ]
