# Generated by Django 5.0 on 2023-12-16 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detail_buku', '0002_like_likes_count'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=set(),
        ),
    ]
