# Generated by Django 4.2.5 on 2023-10-29 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detail_buku', '0002_book_bookmarked_by_book_likes_review_bookmark'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmark',
            name='book',
        ),
        migrations.RemoveField(
            model_name='bookmark',
            name='user',
        ),
        migrations.RemoveField(
            model_name='book',
            name='bookmarked_by',
        ),
        migrations.RemoveField(
            model_name='book',
            name='cover_image',
        ),
        migrations.DeleteModel(
            name='BookBookmark',
        ),
        migrations.DeleteModel(
            name='Bookmark',
        ),
    ]
