# Generated by Django 5.0 on 2023-12-19 15:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_initial'),
        ('my_profile', '0001_initial'),
        ('progress_literasi', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='readinghistory',
            name='books',
            field=models.ManyToManyField(to='progress_literasi.bukudibaca'),
        ),
        migrations.AddField(
            model_name='readinghistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='history_bacaan',
            field=models.ManyToManyField(blank=True, related_name='readers_history', to='home.book'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='reading_list',
            field=models.ManyToManyField(blank=True, related_name='readers', to='home.book'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
