# Generated by Django 4.2.6 on 2023-10-28 05:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('progress_literasi', '0003_alter_aktivitasuser_waktu_aktif_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('my_profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('books', models.ManyToManyField(to='progress_literasi.bukudibaca')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
