# Generated by Django 4.2.6 on 2023-10-29 12:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='readinghistory',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
