# Generated by Django 4.2.6 on 2023-10-29 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_profile', '0002_readinghistory_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='readinghistory',
            name='timestamp',
        ),
    ]
