# Generated by Django 4.2.6 on 2023-10-27 09:55

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('my_profile', '0002_userprofile_target_buku'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='active_time',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_login_timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
