# Generated by Django 4.2.6 on 2023-10-27 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress_literasi', '0004_alter_bukudibaca_buku_alter_progressbaca_buku_and_more'),
        ('my_profile', '0002_readinghistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readinghistory',
            name='books',
            field=models.ManyToManyField(blank=True, to='progress_literasi.bukudibaca'),
        ),
    ]
