# Generated by Django 4.2.6 on 2023-10-27 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_profile', '0003_userprofile_active_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='active_time',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='last_login_timestamp',
        ),
    ]
