# Generated by Django 4.2.6 on 2023-10-27 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_profile', '0005_userprofile_login_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='login_timestamp',
        ),
    ]
