# Generated by Django 4.2.6 on 2023-10-29 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_profile', '0005_remove_userprofile_persentase'),
        ('my_profile', '0006_remove_userprofile_login_timestamp'),
    ]

    operations = [
    ]
